### ISSUE TITLE
Crashes due to change in alive_progress

### ISSUE THREAD

**Issue by denetii** [nlpsuge/NiceCut#2]
Currently, a fresh installation of NiceCut will crash after processing subtitles with the following error:

`ValueError: invalid theme name=ascii`

This is due to the use of `alive_progress` in `main.py`. The 'ascii' theme no longer exists, as it was renamed to 'classic' in this commit: https://github.com/rsalmei/alive-progress/commit/0f43c239d05fd9386e4b1cca9222c74aeab79677#diff-f706a625ea5bd81c477d5ca115d656e03cb4d582e21a0f53d60f39b7354c745d

**Comment by nlpsuge** [comment]
Looking into this issue, reply to you later

**Comment by nlpsuge** [comment]
@denetii 
Hi,
I have committed some code to the `main` branch to fix this issue, the minimum version of alive_progress is 2.0.0 now.

Please uninstall NiceCut at first via `pip uninstall nicecut` in case you still use old version later. 
And install the latest based on the `main` branch via `pip install .`, after this you should use this program without errors.
